using Test
using LibTmux

suite = isempty(ARGS) ? "all" : only(ARGS)
suite in ("unit", "integration", "all") || error("suite must be unit, integration or all")
if suite in ("unit", "all")
    include("server.jl")
    include("process.jl")
    include("cancellation.jl")
    include("text.jl")
    include("model.jl")
    include("criteria.jl")
    include("wire.jl")
    include("sibling_wire.jl")
    include("projection.jl")
    include("format_rows.jl")
    include("control_protocol.jl")
end
if suite in ("integration", "all")
    include("fixture_contract.jl")
    include("lifecycle.jl")
    include("integration.jl")
    include("acquisition.jl")
    include("operations.jl")
    include("pane_io.jl")
    include("topology.jl")
    include("configuration.jl")
    include("formats.jl")
    include("control.jl")
    include("batches.jl")
    include("observation.jl")
    include("control_io.jl")
    include("control_operations.jl")
    include("control_topology.jl")
    include("control_formats.jl")
    include("control_configuration.jl")
end
