using TOML

function generated_criteria(root)
    catalog = TOML.parsefile(joinpath(root, "schema", "fields.toml"))
    catalog["version"] == 1 || error("unsupported field catalog version")
    entities = catalog["entities"]
    source, docs = IOBuffer(), IOBuffer()
    println(source, "# Generated by dev/generate-criteria.jl from schema/fields.toml.")
    println(source, "const _CRITERIA_FIELDS = Dict{Tuple{Symbol,Symbol},_CriteriaField}(")
    for entity in sort!(collect(keys(entities)))
        fields = entities[entity]["fields"]
        names = getindex.(fields, "name")
        length(unique(names)) == length(names) || error("duplicate $(entity) field")
        for field in fields
            name, type = field["name"], field["type"]
            all(x -> occursin(r"\A[a-z][a-z0-9_]*\z", x), (entity, name)) ||
                error("invalid field identifier")
            type in (
                "String",
                "Integer",
                "Bool",
                "PaneID",
                "WindowID",
                "SessionID",
                "ClientID",
                "relation",
            ) || error("invalid field type")
            relation, target = get(field, "relation", "scalar"), get(field, "target", "any")
            relation in ("scalar", "one", "many") || error("invalid relation kind")
            (type == "relation") == (relation != "scalar") ||
                error("inconsistent field relation")
            relation == "scalar" ||
                haskey(entities, target) ||
                error("unknown relation target")
            nullable = get(field, "nullable", false)
            println(
                source,
                "    (:",
                entity,
                ", :",
                name,
                ") => _CriteriaField(:",
                type,
                ", ",
                nullable,
                ", :",
                relation,
                ", :",
                target,
                "),",
            )
        end
    end
    println(source, ")\n")
    println(source, "const _WIRE_FIELDS = Dict{String,Tuple{Symbol,Symbol}}(")
    wire_names = Set{String}()
    for entity in sort!(collect(keys(entities)))
        for field in entities[entity]["fields"]
            wire = field["wire"]
            occursin(r"\Atmux\.[a-z]+\.[a-z][a-z0-9_]*\z", wire) ||
                error("invalid wire identity")
            wire in wire_names && error("duplicate wire identity")
            push!(wire_names, wire)
            println(
                source,
                "    ",
                repr(wire),
                " => (:",
                entity,
                ", :",
                field["name"],
                "),",
            )
        end
    end
    println(
        source,
        ")\nconst _FIELD_WIRE = Dict(value => key for (key, value) in _WIRE_FIELDS)\n",
    )
    println(docs, "# Criteria field reference\n")
    println(
        docs,
        "Generated from `schema/fields.toml`; regenerate with `dev/generate-criteria.jl`.\n",
    )
    println(
        docs,
        "Criteria are local callable values. Omitted keywords impose no constraint.",
    )
    println(docs, "`nothing` matches captured absence only for nullable fields; uncaptured")
    println(
        docs,
        "values raise `SnapshotCoverageError`. IDs require their typed constructors.\n",
    )
    println(
        docs,
        "Import operators with `import LibTmux.Filters as F`. Scalar fields accept",
    )
    println(
        docs,
        "bare equality, `F.EqualTo`, `F.NotEqualTo`, and `F.OneOf`. String fields also",
    )
    println(
        docs,
        "accept `F.Contains`, `F.StartsWith`, and `F.EndsWith`; their `case` option is",
    )
    println(
        docs,
        "`:sensitive` or `:ascii_insensitive`, without Unicode folding. Integer fields",
    )
    println(
        docs,
        "accept `F.AtLeast`, `F.AtMost`, `F.GreaterThan`, and `F.LessThan` with finite",
    )
    println(docs, "numeric thresholds; Boolean values are not numeric operands.\n")
    println(
        docs,
        "To-one relations accept a nested criterion; optional relations also accept",
    )
    println(
        docs,
        "equality/inequality with `nothing`. To-many relations require `F.AnyRelated`,",
    )
    println(
        docs,
        "`F.AllRelated`, or `F.NoRelated`. Empty membership gives false/true/true.",
    )
    println(docs, "`F.AllOf`, `F.AnyOf`, and `F.Not` combine criteria for the same entity.")
    println(
        docs,
        "All branches and related members are checked for coverage before matching.\n",
    )
    for entity in sort!(collect(keys(entities)))
        spec = entities[entity]
        constructor, observation = spec["constructor"], spec["observation"]
        for name in (constructor, observation)
            occursin(r"\A[A-Z][A-Za-z0-9]*\z", name) || error("invalid type identifier")
        end
        fields = spec["fields"]
        names = getindex.(fields, "name")
        println(source, "\"\"\"\n    ", constructor, "(; ", join(names, ", "), ")\n")
        println(
            source,
            "Match captured `",
            observation,
            "` values without I/O. Omitted keywords are",
        )
        println(
            source,
            "unconstrained. Explicit `nothing` requires nullable captured absence.",
        )
        println(
            source,
            "All specified fields and related records are checked for coverage first.\n",
        )
        println(source, "Keywords:\n")
        for f in fields
            println(source, "- `", f["name"], "` (", f["type"], "): ", f["summary"])
        end
        println(source, "\"\"\"")
        println(
            source,
            "struct ",
            constructor,
            " <: Criterion\n    _clauses::Tuple{Vararg{_FieldClause}}",
        )
        println(
            source,
            "    ",
            constructor,
            "(clauses::Tuple{Vararg{_FieldClause}}, ::Val{:validated}) = new(clauses)\nend",
        )
        println(
            source,
            "function ",
            constructor,
            "(; ",
            join((n * "=_UNCONSTRAINED" for n in names), ", "),
            ")",
        )
        println(
            source,
            "    ",
            constructor,
            "(_where_clauses(:",
            entity,
            ", (; ",
            join(names, ", "),
            ")), Val(:validated))\nend",
        )
        println(source, "_criterion_entity(::", constructor, ") = :", entity)
        println(source, "_observation_entity(::Type{", observation, "}) = :", entity, "\n")
        println(docs, "## ", constructor, "\n")
        println(
            docs,
            "Matches `",
            observation,
            "`. All listed fields use local evaluation; tmux",
        )
        println(
            docs,
            "pushdown is not implemented. Availability depends on captured coverage.\n",
        )
        println(
            docs,
            "| Keyword | Wire identity | Julia value | Nullable | tmux field/source | Contract |\n| --- | --- | --- | --- | --- | --- |",
        )
        for f in fields
            type =
                f["type"] == "relation" ?
                entities[f["target"]]["constructor"] * " (" * f["relation"] * ")" :
                f["type"]
            println(
                docs,
                "| `",
                f["name"],
                "` | `",
                f["wire"],
                "` | `",
                type,
                "` | ",
                get(f, "nullable", false),
                " | `",
                f["tmux"],
                "` | ",
                f["summary"],
                " ",
                get(f, "availability", ""),
                " |",
            )
        end
        println(docs)
    end
    rstrip(String(take!(source))) * "\n", rstrip(String(take!(docs))) * "\n"
end

function main(args)
    args in (String[], ["--check"]) || error("usage: generate-criteria.jl [--check]")
    root = dirname(@__DIR__)
    code, docs = generated_criteria(root)
    outputs = ("src/criteria_generated.jl" => code, "docs/generated/criteria.md" => docs)
    if args == ["--check"]
        for (path, expected) in outputs
            actual = joinpath(root, path)
            isfile(actual) && read(actual, String) == expected ||
                error("generated file is stale: $path")
        end
        println("criteria generation is current")
    else
        for (path, contents) in outputs
            destination = joinpath(root, path)
            mkpath(dirname(destination))
            write(destination, contents)
        end
    end
end

abspath(PROGRAM_FILE) == (@__FILE__) && main(ARGS)
