# Generated by dev/generate-criteria.jl from schema/fields.toml.
const _CRITERIA_FIELDS = Dict{Tuple{Symbol,Symbol},_CriteriaField}(
    (:client, :id) => _CriteriaField(:ClientID, false, :scalar, :any),
    (:client, :name) => _CriteriaField(:String, false, :scalar, :any),
    (:client, :pid) => _CriteriaField(:Integer, false, :scalar, :any),
    (:client, :created) => _CriteriaField(:Integer, false, :scalar, :any),
    (:client, :session) => _CriteriaField(:relation, true, :one, :session),
    (:pane, :id) => _CriteriaField(:PaneID, false, :scalar, :any),
    (:pane, :index) => _CriteriaField(:Integer, false, :scalar, :any),
    (:pane, :active) => _CriteriaField(:Bool, false, :scalar, :any),
    (:pane, :dead) => _CriteriaField(:Bool, false, :scalar, :any),
    (:pane, :width) => _CriteriaField(:Integer, false, :scalar, :any),
    (:pane, :height) => _CriteriaField(:Integer, false, :scalar, :any),
    (:pane, :current_command) => _CriteriaField(:String, true, :scalar, :any),
    (:pane, :current_path) => _CriteriaField(:String, true, :scalar, :any),
    (:pane, :title) => _CriteriaField(:String, false, :scalar, :any),
    (:pane, :window) => _CriteriaField(:relation, false, :one, :window),
    (:session, :id) => _CriteriaField(:SessionID, false, :scalar, :any),
    (:session, :name) => _CriteriaField(:String, false, :scalar, :any),
    (:session, :attached_clients) => _CriteriaField(:Integer, false, :scalar, :any),
    (:session, :windows) => _CriteriaField(:relation, false, :many, :window),
    (:session, :windowlinks) => _CriteriaField(:relation, false, :many, :windowlink),
    (:window, :id) => _CriteriaField(:WindowID, false, :scalar, :any),
    (:window, :name) => _CriteriaField(:String, false, :scalar, :any),
    (:window, :width) => _CriteriaField(:Integer, false, :scalar, :any),
    (:window, :height) => _CriteriaField(:Integer, false, :scalar, :any),
    (:window, :panes) => _CriteriaField(:relation, false, :many, :pane),
    (:window, :windowlinks) => _CriteriaField(:relation, false, :many, :windowlink),
    (:windowlink, :index) => _CriteriaField(:Integer, false, :scalar, :any),
    (:windowlink, :active) => _CriteriaField(:Bool, false, :scalar, :any),
    (:windowlink, :session) => _CriteriaField(:relation, false, :one, :session),
    (:windowlink, :window) => _CriteriaField(:relation, false, :one, :window),
)

const _WIRE_FIELDS = Dict{String,Tuple{Symbol,Symbol}}(
    "tmux.client.id" => (:client, :id),
    "tmux.client.name" => (:client, :name),
    "tmux.client.pid" => (:client, :pid),
    "tmux.client.created" => (:client, :created),
    "tmux.client.session" => (:client, :session),
    "tmux.pane.id" => (:pane, :id),
    "tmux.pane.index" => (:pane, :index),
    "tmux.pane.active" => (:pane, :active),
    "tmux.pane.dead" => (:pane, :dead),
    "tmux.pane.width" => (:pane, :width),
    "tmux.pane.height" => (:pane, :height),
    "tmux.pane.current_command" => (:pane, :current_command),
    "tmux.pane.current_path" => (:pane, :current_path),
    "tmux.pane.title" => (:pane, :title),
    "tmux.pane.window" => (:pane, :window),
    "tmux.session.id" => (:session, :id),
    "tmux.session.name" => (:session, :name),
    "tmux.session.attached_clients" => (:session, :attached_clients),
    "tmux.session.windows" => (:session, :windows),
    "tmux.session.windowlinks" => (:session, :windowlinks),
    "tmux.window.id" => (:window, :id),
    "tmux.window.name" => (:window, :name),
    "tmux.window.width" => (:window, :width),
    "tmux.window.height" => (:window, :height),
    "tmux.window.panes" => (:window, :panes),
    "tmux.window.windowlinks" => (:window, :windowlinks),
    "tmux.windowlink.index" => (:windowlink, :index),
    "tmux.windowlink.active" => (:windowlink, :active),
    "tmux.windowlink.session" => (:windowlink, :session),
    "tmux.windowlink.window" => (:windowlink, :window),
)
const _FIELD_WIRE = Dict(value => key for (key, value) in _WIRE_FIELDS)

"""
    ClientWhere(; id, name, pid, created, session)

Match captured `ClientSnapshot` values without I/O. Omitted keywords are
unconstrained. Explicit `nothing` requires nullable captured absence.
All specified fields and related records are checked for coverage first.

Keywords:

- `id` (ClientID): Exact name plus observed connection incarnation.
- `name` (String): Exact tmux client name.
- `pid` (Integer): Observed client process ID.
- `created` (Integer): Observed creation time; not a strict identity guard.
- `session` (relation): Captured session or known absence; normal acquisition lists attached clients.
"""
struct ClientWhere <: Criterion
    _clauses::Tuple{Vararg{_FieldClause}}
    ClientWhere(clauses::Tuple{Vararg{_FieldClause}}, ::Val{:validated}) = new(clauses)
end
function ClientWhere(; id=_UNCONSTRAINED, name=_UNCONSTRAINED, pid=_UNCONSTRAINED, created=_UNCONSTRAINED, session=_UNCONSTRAINED)
    ClientWhere(_where_clauses(:client, (; id, name, pid, created, session)), Val(:validated))
end
_criterion_entity(::ClientWhere) = :client
_observation_entity(::Type{ClientSnapshot}) = :client

"""
    PaneWhere(; id, index, active, dead, width, height, current_command, current_path, title, window)

Match captured `PaneSnapshot` values without I/O. Omitted keywords are
unconstrained. Explicit `nothing` requires nullable captured absence.
All specified fields and related records are checked for coverage first.

Keywords:

- `id` (PaneID): Physical pane identity.
- `index` (Integer): Pane index within its window; not a Julia collection position.
- `active` (Bool): Active pane of its window; not client visibility.
- `dead` (Bool): Whether tmux retains an exited pane.
- `width` (Integer): Pane width in cells.
- `height` (Integer): Pane height in cells.
- `current_command` (String): Command name observed by tmux.
- `current_path` (String): Path observed on the tmux host; text matching is lexical.
- `title` (String): Pane title, including literal format-like text.
- `window` (relation): Physical containing window.
"""
struct PaneWhere <: Criterion
    _clauses::Tuple{Vararg{_FieldClause}}
    PaneWhere(clauses::Tuple{Vararg{_FieldClause}}, ::Val{:validated}) = new(clauses)
end
function PaneWhere(; id=_UNCONSTRAINED, index=_UNCONSTRAINED, active=_UNCONSTRAINED, dead=_UNCONSTRAINED, width=_UNCONSTRAINED, height=_UNCONSTRAINED, current_command=_UNCONSTRAINED, current_path=_UNCONSTRAINED, title=_UNCONSTRAINED, window=_UNCONSTRAINED)
    PaneWhere(_where_clauses(:pane, (; id, index, active, dead, width, height, current_command, current_path, title, window)), Val(:validated))
end
_criterion_entity(::PaneWhere) = :pane
_observation_entity(::Type{PaneSnapshot}) = :pane

"""
    SessionWhere(; id, name, attached_clients, windows, windowlinks)

Match captured `SessionSnapshot` values without I/O. Omitted keywords are
unconstrained. Explicit `nothing` requires nullable captured absence.
All specified fields and related records are checked for coverage first.

Keywords:

- `id` (SessionID): Session identity.
- `name` (String): Session name.
- `attached_clients` (Integer): Attached client count observed by tmux.
- `windows` (relation): Unique windows reached through complete captured session links.
- `windowlinks` (relation): Complete captured links including session-specific indices.
"""
struct SessionWhere <: Criterion
    _clauses::Tuple{Vararg{_FieldClause}}
    SessionWhere(clauses::Tuple{Vararg{_FieldClause}}, ::Val{:validated}) = new(clauses)
end
function SessionWhere(; id=_UNCONSTRAINED, name=_UNCONSTRAINED, attached_clients=_UNCONSTRAINED, windows=_UNCONSTRAINED, windowlinks=_UNCONSTRAINED)
    SessionWhere(_where_clauses(:session, (; id, name, attached_clients, windows, windowlinks)), Val(:validated))
end
_criterion_entity(::SessionWhere) = :session
_observation_entity(::Type{SessionSnapshot}) = :session

"""
    WindowWhere(; id, name, width, height, panes, windowlinks)

Match captured `WindowSnapshot` values without I/O. Omitted keywords are
unconstrained. Explicit `nothing` requires nullable captured absence.
All specified fields and related records are checked for coverage first.

Keywords:

- `id` (WindowID): Physical window identity, independent of session links.
- `name` (String): Window name.
- `width` (Integer): Window width in cells.
- `height` (Integer): Window height in cells.
- `panes` (relation): Complete captured physical pane membership.
- `windowlinks` (relation): Complete captured links to sessions.
"""
struct WindowWhere <: Criterion
    _clauses::Tuple{Vararg{_FieldClause}}
    WindowWhere(clauses::Tuple{Vararg{_FieldClause}}, ::Val{:validated}) = new(clauses)
end
function WindowWhere(; id=_UNCONSTRAINED, name=_UNCONSTRAINED, width=_UNCONSTRAINED, height=_UNCONSTRAINED, panes=_UNCONSTRAINED, windowlinks=_UNCONSTRAINED)
    WindowWhere(_where_clauses(:window, (; id, name, width, height, panes, windowlinks)), Val(:validated))
end
_criterion_entity(::WindowWhere) = :window
_observation_entity(::Type{WindowSnapshot}) = :window

"""
    WindowLinkWhere(; index, active, session, window)

Match captured `WindowLink` values without I/O. Omitted keywords are
unconstrained. Explicit `nothing` requires nullable captured absence.
All specified fields and related records are checked for coverage first.

Keywords:

- `index` (Integer): Window index in this session.
- `active` (Bool): Selected window in this session.
- `session` (relation): Session containing this link.
- `window` (relation): Physical linked window.
"""
struct WindowLinkWhere <: Criterion
    _clauses::Tuple{Vararg{_FieldClause}}
    WindowLinkWhere(clauses::Tuple{Vararg{_FieldClause}}, ::Val{:validated}) = new(clauses)
end
function WindowLinkWhere(; index=_UNCONSTRAINED, active=_UNCONSTRAINED, session=_UNCONSTRAINED, window=_UNCONSTRAINED)
    WindowLinkWhere(_where_clauses(:windowlink, (; index, active, session, window)), Val(:validated))
end
_criterion_entity(::WindowLinkWhere) = :windowlink
_observation_entity(::Type{WindowLink}) = :windowlink
